services:
  - type: web
    name: baccarat-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMINS
        value: "1190237801"
      - key: PORT
        value: "10000"
      - key: TELETHON_API_ID
        value: "29177661"
      - key: TELETHON_API_HASH
        sync: false
      - key: TELETHON_SESSION
        sync: false
